// This file was automatically generated by `scripts/precalculate.ts`.

import {
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_0_0,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_0_1,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_0_2,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_1_0,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_1_1,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_1_2,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_2_0,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_2_1,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_2_2,
} from "../../matrices";

/**
 * Calculates the X component of CIE 1931 XYZ from linear DCI-P3 "D60 sim".
 *
 * @param r The red component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 * @param g The green component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 * @param b The blue component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 *
 * @returns The X component of CIE 1931 XYZ.
 */
export const toCIE1931XYZXFromLinearDCIP3D60 = (
    r: number,
    g: number,
    b: number,
) => r * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_0_0
    + g * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_0_1
    + b * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_0_2;

/**
 * Calculates the Y component of CIE 1931 XYZ from linear DCI-P3 "D60 sim".
 *
 * @param r The red component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 * @param g The green component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 * @param b The blue component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 *
 * @returns The Y component of CIE 1931 XYZ.
 */
export const toCIE1931XYZYFromLinearDCIP3D60 = (
    r: number,
    g: number,
    b: number,
) => r * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_1_0
    + g * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_1_1
    + b * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_1_2;

/**
 * Calculates the Z component of CIE 1931 XYZ from linear DCI-P3 "D60 sim".
 *
 * @param r The red component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 * @param g The green component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 * @param b The blue component of linear DCI-P3 "D60 sim", typically in the range [0, 1].
 *
 * @returns The Z component of CIE 1931 XYZ.
 */
export const toCIE1931XYZZFromLinearDCIP3D60 = (
    r: number,
    g: number,
    b: number,
) => r * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_2_0
    + g * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_2_1
    + b * MATRIX_CIE_1931_XYZ_FROM_LINEAR_DCI_P3_D60_2_2;