// This file was generated by `scripts/precalculate.ts`.

import {clamp01} from "../../internal";
import {
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_0_0,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_0_1,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_0_2,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_1_0,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_1_1,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_1_2,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_2_0,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_2_1,
    MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_2_2,
} from "../../matrices";

/**
 * Calculates the red component of linear ProPhoto RGB from CIE 1931 XYZ.
 *
 * @param x The X component of CIE 1931 XYZ.
 * @param y The Y component of CIE 1931 XYZ.
 * @param z The Z component of CIE 1931 XYZ.
 *
 * @returns The red component of linear ProPhoto RGB.
 */
export const toLinearProPhotoRGBRFromCIE1931XYZ = (
    x: number,
    y: number,
    z: number,
) =>
    clamp01(
        x * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_0_0 +
            y * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_0_1 +
            z * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_0_2,
    );

/**
 * Calculates the green component of linear ProPhoto RGB from CIE 1931 XYZ.
 *
 * @param x The X component of CIE 1931 XYZ.
 * @param y The Y component of CIE 1931 XYZ.
 * @param z The Z component of CIE 1931 XYZ.
 *
 * @returns The green component of linear ProPhoto RGB.
 */
export const toLinearProPhotoRGBGFromCIE1931XYZ = (
    x: number,
    y: number,
    z: number,
) =>
    clamp01(
        x * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_1_0 +
            y * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_1_1 +
            z * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_1_2,
    );

/**
 * Calculates the blue component of linear ProPhoto RGB from CIE 1931 XYZ.
 *
 * @param x The X component of CIE 1931 XYZ.
 * @param y The Y component of CIE 1931 XYZ.
 * @param z The Z component of CIE 1931 XYZ.
 *
 * @returns The blue component of linear ProPhoto RGB.
 */
export const toLinearProPhotoRGBBFromCIE1931XYZ = (
    x: number,
    y: number,
    z: number,
) =>
    clamp01(
        x * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_2_0 +
            y * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_2_1 +
            z * MATRIX_LINEAR_PRO_PHOTO_RGB_FROM_CIE_1931_XYZ_2_2,
    );
