import {writeFile} from "node:fs/promises";
import Matrix, {inverse} from "ml-matrix";
import {
    toCIE1931XYZXFromCIE1931xyY,
    toCIE1931XYZZFromCIE1931xyY,
} from "../src/conversions/cie-1931-xyy";
import * as illuminants from "../src/illuminants";
import * as extractedMatrices from "../src/matrices/extracted";
import * as primaries from "../src/primaries";

const constants = new Map<string, number>();

const addSquareMatrix = (id: string, matrix: number[]) => {
    const n = Math.sqrt(matrix.length);

    for (let row = 0; row < n; row++) {
        for (let col = 0; col < n; col++) {
            constants.set(
                `MATRIX_${id}_${row}_${col}`,
                matrix[row * n + col] ?? 0,
            );
        }
    }
};

const calculateLinearRGBToCIE1931XYZMatrix = (
    red_x: number,
    red_y: number,
    green_x: number,
    green_y: number,
    blue_x: number,
    blue_y: number,
    illuminant_x: number,
    illuminant_y: number,
) => {
    const illuminant_Y = 1;
    const illuminant_X = toCIE1931XYZXFromCIE1931xyY(
        illuminant_x,
        illuminant_y,
        illuminant_Y,
    );
    const illuminant_Z = toCIE1931XYZZFromCIE1931xyY(
        illuminant_x,
        illuminant_y,
        illuminant_Y,
    );

    const red_X = toCIE1931XYZXFromCIE1931xyY(red_x, red_y, 1);
    const red_Z = toCIE1931XYZZFromCIE1931xyY(red_x, red_y, 1);

    const green_X = toCIE1931XYZXFromCIE1931xyY(green_x, green_y, 1);
    const green_Z = toCIE1931XYZZFromCIE1931xyY(green_x, green_y, 1);

    const blue_X = toCIE1931XYZXFromCIE1931xyY(blue_x, blue_y, 1);
    const blue_Z = toCIE1931XYZZFromCIE1931xyY(blue_x, blue_y, 1);

    const primaries = new Matrix([
        [red_X, 1, red_Z],
        [green_X, 1, green_Z],
        [blue_X, 1, blue_Z],
    ]).transpose();

    const primariesInverse = inverse(primaries);

    const scaling = primariesInverse.mmul(
        new Matrix([[illuminant_X], [illuminant_Y], [illuminant_Z]]),
    );

    return primaries.mmul(
        new Matrix([
            [scaling.get(0, 0), 0, 0],
            [0, scaling.get(1, 0), 0],
            [0, 0, scaling.get(2, 0)],
        ]),
    );
};

const addInverseMatrixOfExtracted = (to: string, from: string) => {
    const mat = Matrix.from1DArray(3, 3, [
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_0_0`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_0_1`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_0_2`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_1_0`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_1_1`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_1_2`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_2_0`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_2_1`],
        // @ts-expect-error
        extractedMatrices[`MATRIX_${to}_FROM_${from}_2_2`],
    ]);

    addSquareMatrix(`${from}_FROM_${to}`, inverse(mat).to1DArray());
};

const fileTextToCIE1931XYZFromLinearRGBColorSpace = (
    uppercase: string,
    text: string,
    pascalcase: string,
) => `// This file was automatically generated by \`scripts/precalculate.ts\`.

import {
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_0_0,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_0_1,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_0_2,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_1_0,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_1_1,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_1_2,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_2_0,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_2_1,
    MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_2_2,
} from "../../matrices";

/**
 * Calculates the X component of CIE 1931 XYZ from linear ${text}.
 *
 * @param r The red component of linear ${text}, typically in the range [0, 1].
 * @param g The green component of linear ${text}, typically in the range [0, 1].
 * @param b The blue component of linear ${text}, typically in the range [0, 1].
 *
 * @returns The X component of CIE 1931 XYZ.
 */
export const toCIE1931XYZXFromLinear${pascalcase} = (
    r: number,
    g: number,
    b: number,
) => r * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_0_0
    + g * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_0_1
    + b * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_0_2;

/**
 * Calculates the Y component of CIE 1931 XYZ from linear ${text}.
 *
 * @param r The red component of linear ${text}, typically in the range [0, 1].
 * @param g The green component of linear ${text}, typically in the range [0, 1].
 * @param b The blue component of linear ${text}, typically in the range [0, 1].
 *
 * @returns The Y component of CIE 1931 XYZ.
 */
export const toCIE1931XYZYFromLinear${pascalcase} = (
    r: number,
    g: number,
    b: number,
) => r * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_1_0
    + g * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_1_1
    + b * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_1_2;

/**
 * Calculates the Z component of CIE 1931 XYZ from linear ${text}.
 *
 * @param r The red component of linear ${text}, typically in the range [0, 1].
 * @param g The green component of linear ${text}, typically in the range [0, 1].
 * @param b The blue component of linear ${text}, typically in the range [0, 1].
 *
 * @returns The Z component of CIE 1931 XYZ.
 */
export const toCIE1931XYZZFromLinear${pascalcase} = (
    r: number,
    g: number,
    b: number,
) => r * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_2_0
    + g * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_2_1
    + b * MATRIX_CIE_1931_XYZ_FROM_LINEAR_${uppercase}_2_2;`;

const fileTextToLinearRGBColorSpaceFromCIE1931XYZ = (
    upperCase: string,
    text: string,
    pascalCase: string,
) => `// This file was generated by \`scripts/precalculate.ts\`.

import {clamp01} from "../../internal";
import {
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_0_0,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_0_1,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_0_2,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_1_0,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_1_1,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_1_2,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_2_0,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_2_1,
    MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_2_2,
} from "../../matrices";

/**
 * Calculates the red component of linear ${text} from CIE 1931 XYZ.
 *
 * @param x The X component of CIE 1931 XYZ.
 * @param y The Y component of CIE 1931 XYZ.
 * @param z The Z component of CIE 1931 XYZ.
 *
 * @returns The red component of linear ${text}, clamped to [0, 1].
 */
export const toLinear${pascalCase}RFromCIE1931XYZ = (
    x: number,
    y: number,
    z: number,
) => clamp01(x * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_0_0
    + y * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_0_1
    + z * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_0_2);

/**
 * Calculates the green component of linear ${text} from CIE 1931 XYZ.
 *
 * @param x The X component of CIE 1931 XYZ.
 * @param y The Y component of CIE 1931 XYZ.
 * @param z The Z component of CIE 1931 XYZ.
 *
 * @returns The green component of linear ${text}, clamped to [0, 1].
 */
export const toLinear${pascalCase}GFromCIE1931XYZ = (
    x: number,
    y: number,
    z: number,
) => clamp01(x * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_1_0
    + y * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_1_1
    + z * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_1_2);

/**
 * Calculates the blue component of linear ${text} from CIE 1931 XYZ.
 *
 * @param x The X component of CIE 1931 XYZ.
 * @param y The Y component of CIE 1931 XYZ.
 * @param z The Z component of CIE 1931 XYZ.
 *
 * @returns The blue component of linear ${text}, clamped to [0, 1].
 */
export const toLinear${pascalCase}BFromCIE1931XYZ = (
    x: number,
    y: number,
    z: number,
) => clamp01(x * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_2_0
    + y * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_2_1
    + z * MATRIX_LINEAR_${upperCase}_FROM_CIE_1931_XYZ_2_2);`;

const addRGBColorSpace = async ({
    fileCase,
    matrix,
    pascalCase,
    text,
    upperCase,
}: {
    matrix:
        | {
              type: "generated";
              illuminant: string;
              primariesId: string;
          }
        | {
              type: "extracted";
          };
    upperCase: string;
    text: string;
    pascalCase: string;
    fileCase: string;
}) => {
    let linearRGBToCIE1931XYZMatrix: Matrix;

    if (matrix.type === "generated") {
        // Generate the matrix from primaries.

        linearRGBToCIE1931XYZMatrix = calculateLinearRGBToCIE1931XYZMatrix(
            // @ts-expect-error
            primaries[`PRIMARY_${primariesId}_RED_x`],
            // @ts-expect-error
            primaries[`PRIMARY_${primariesId}_RED_y`],
            // @ts-expect-error
            primaries[`PRIMARY_${primariesId}_GREEN_x`],
            // @ts-expect-error
            primaries[`PRIMARY_${primariesId}_GREEN_y`],
            // @ts-expect-error
            primaries[`PRIMARY_${primariesId}_BLUE_x`],
            // @ts-expect-error
            primaries[`PRIMARY_${primariesId}_BLUE_y`],
            // @ts-expect-error
            illuminants[`${illuminant}_x`],
            // @ts-expect-error
            illuminants[`${illuminant}_x`],
        );

        addSquareMatrix(
            `CIE_1931_XYZ_FROM_LINEAR_${upperCase}`,
            linearRGBToCIE1931XYZMatrix.to1DArray(),
        );

        addSquareMatrix(
            `LINEAR_${upperCase}_FROM_CIE_1931_XYZ`,
            inverse(linearRGBToCIE1931XYZMatrix).to1DArray(),
        );
    } else {
        addInverseMatrixOfExtracted(upperCase, "CIE_1931_XYZ");
    }

    await Promise.all([
        writeFile(
            `./src/conversions/cie-1931-xyz/to-linear-${fileCase}.ts`,
            fileTextToLinearRGBColorSpaceFromCIE1931XYZ(
                upperCase,
                text,
                pascalCase,
            ),
        ),
        writeFile(
            `./src/conversions/linear-rgb/${fileCase}-to-cie-1931-xyz.ts`,
            fileTextToCIE1931XYZFromLinearRGBColorSpace(
                upperCase,
                text,
                pascalCase,
            ),
        ),
    ]);
};

// --------------------------------------------------------

await Promise.all([
    addRGBColorSpace({
        pascalCase: "SRGB",
        text: "sRGB",
        fileCase: "srgb",
        upperCase: "SRGB",
        matrix: {
            type: "extracted",
        },
    }),
    addRGBColorSpace({
        fileCase: "adobe-rgb",
        pascalCase: "AdobeRGB",
        text: "Adobe RGB",
        upperCase: "ADOBE_RGB",
        matrix: {
            type: "extracted",
        },
    }),
    addRGBColorSpace({
        fileCase: "dci-p3",
        pascalCase: "DCIP3",
        text: "DCI-P3",
        upperCase: "DCI_P3",
        matrix: {
            type: "generated",
            illuminant: "ILLUMINANT_D63_2d",
            primariesId: "DCI_P3",
        },
    }),
    addRGBColorSpace({
        fileCase: "dci-p3-d60",
        pascalCase: "DCIP3D60",
        text: `DCI-P3 "D60 sim"`,
        upperCase: "DCI_P3_D60",
        matrix: {
            type: "generated",
            illuminant: "CIE_ILLUMINANT_D60_2d",
            primariesId: "PCI_P3",
        },
    }),
    addRGBColorSpace({
        fileCase: "display-p3",
        pascalCase: "DisplayP3",
        text: "Display P3",
        upperCase: "DISPLAY_P3",
        matrix: {
            type: "extracted",
        },
    }),
    addRGBColorSpace({
        fileCase: "rec-2020",
        pascalCase: "Rec2020",
        text: "Rec. 2020",
        upperCase: "REC_2020",
        matrix: {
            type: "extracted",
        },
    }),
    addRGBColorSpace({
        fileCase: "prophoto-rgb",
        pascalCase: "ProPhotoRGB",
        text: "ProPhoto RGB",
        upperCase: "PRO_PHOTO_RGB",
        matrix: {
            type: "extracted",
        },
    }),
    addRGBColorSpace({
        fileCase: "ntsc",
        pascalCase: "NTSC",
        text: "NTSC (1953)",
        upperCase: "NTSC",
        matrix: {
            type: "generated",
            illuminant: "CIE_ILLUMINANT_C_2d",
            primariesId: "NTSC",
        },
    }),
    addRGBColorSpace({
        fileCase: "smpte-c",
        pascalCase: "SMPTEC",
        text: "SMPTE C (1987)",
        upperCase: "SMPTE_C",
        matrix: {
            type: "generated",
            illuminant: "CIE_ILLUMINANT_D65_2d",
            primariesId: "SMPTE_C",
        },
    }),
]);

addInverseMatrixOfExtracted("YIQ_FCC", "RGB");
addInverseMatrixOfExtracted("YIQ_1953", "RGB");
addInverseMatrixOfExtracted("YDbDr", "RGB");

// --------------------------------------------------------

await writeFile(
    "./src/matrices/generated.ts",
    "// This file was automatically generated by `src-comptime/precalculate.ts` in the root of the repo.\n" +
        Array.from(constants.entries())
            .map(
                ([id, value]) =>
                    `export const ${id} = ${JSON.stringify(value)};`,
            )
            .reduce((a, b) => `${a}\n${b}`, ""),
);
